/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import com.example.senura.lipermitest1.ServerConnection;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author senura
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        buttonSendDDOS.setEnabled(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSendDDOS = new javax.swing.JButton();
        buttonStartConnection = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(612, 672));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(612, 672));
        getContentPane().setLayout(null);

        buttonSendDDOS.setText("Send DDOS");
        buttonSendDDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendDDOSActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSendDDOS);
        buttonSendDDOS.setBounds(150, 290, 290, 90);

        buttonStartConnection.setText("Start Connection");
        buttonStartConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonStartConnection);
        buttonStartConnection.setBounds(190, 80, 210, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendDDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendDDOSActionPerformed

//        if(ServerConnection.closeTheConnection()){
//            buttonSendDDOS.setEnabled(false);
//        }

     ServerConnection.setDDOSURL("https://httpbin.org/ip");



    }//GEN-LAST:event_buttonSendDDOSActionPerformed

    private void buttonStartConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartConnectionActionPerformed
        // TODO add your handling code here:

            boolean isServerStarted = ServerConnection.start();
            
            if(isServerStarted)  buttonSendDDOS.setEnabled(true);
           
        
    }//GEN-LAST:event_buttonStartConnectionActionPerformed

    
    
    
    public void restartApplication() throws URISyntaxException, IOException
{
  final String javaBin = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";
  final File currentJar = new File(MainMenu.class.getProtectionDomain().getCodeSource().getLocation().toURI());

  /* is it a jar file? */
  if(!currentJar.getName().endsWith(".jar"))
    return;

  /* Build command: java -jar application.jar */
  final ArrayList<String> command = new ArrayList<String>();
  command.add(javaBin);
  command.add("-jar");
  command.add(currentJar.getPath());

  final ProcessBuilder builder = new ProcessBuilder(command);
  builder.start();
  System.exit(0);
}
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSendDDOS;
    private javax.swing.JButton buttonStartConnection;
    // End of variables declaration//GEN-END:variables
}
