/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import com.example.senura.lipermitest1.ClientControllerCon;
import com.example.senura.lipermitest1.ServerConnection;
import com.example.senura.lipermitest1.URLValidate;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author senura
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        buttonSendDDOS.setEnabled(false);
        jButton_startDDOSAttck.setEnabled(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSendDDOS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonStartConnection = new javax.swing.JButton();
        jTextField_HostAddress = new javax.swing.JTextField();
        jScrollPane_Status = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();
        jScrollPane_ClientStatus = new javax.swing.JScrollPane();
        jTextArea_ClientStatus = new javax.swing.JTextArea();
        jButton_startDDOSAttck = new javax.swing.JButton();
        jTextField_numOfAttcks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_RewardsStatusText = new javax.swing.JTextArea();
        jLabel_ConnectedBots = new javax.swing.JLabel();
        jLabel_DDOSURL1 = new javax.swing.JLabel();
        jLabel_ServerStatus1 = new javax.swing.JLabel();
        jLabel_ConnectedBots1 = new javax.swing.JLabel();
        jLabel_ConnectedBots2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(612, 682));
        setPreferredSize(new java.awt.Dimension(600, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(612, 672));
        getContentPane().setLayout(null);

        buttonSendDDOS.setText("Set DDOS URL");
        buttonSendDDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendDDOSActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSendDDOS);
        buttonSendDDOS.setBounds(480, 150, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/robot_1_small.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 210, 130, 180);

        buttonStartConnection.setText("Start Connection");
        buttonStartConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonStartConnection);
        buttonStartConnection.setBounds(20, 80, 570, 60);

        jTextField_HostAddress.setForeground(new java.awt.Color(0, 51, 102));
        jTextField_HostAddress.setText("https://httpbin.org/user-agent");
        jTextField_HostAddress.setToolTipText("Type the Host Url here");
        jTextField_HostAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HostAddressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_HostAddress);
        jTextField_HostAddress.setBounds(140, 150, 340, 40);

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setForeground(new java.awt.Color(0, 51, 102));
        jTextAreaStatus.setRows(5);
        jScrollPane_Status.setViewportView(jTextAreaStatus);

        getContentPane().add(jScrollPane_Status);
        jScrollPane_Status.setBounds(20, 220, 430, 130);

        jTextArea_ClientStatus.setEditable(false);
        jTextArea_ClientStatus.setColumns(20);
        jTextArea_ClientStatus.setForeground(new java.awt.Color(0, 51, 102));
        jTextArea_ClientStatus.setRows(5);
        jScrollPane_ClientStatus.setViewportView(jTextArea_ClientStatus);

        getContentPane().add(jScrollPane_ClientStatus);
        jScrollPane_ClientStatus.setBounds(20, 380, 570, 100);

        jButton_startDDOSAttck.setText("Start DDOS Attack");
        jButton_startDDOSAttck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startDDOSAttckActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_startDDOSAttck);
        jButton_startDDOSAttck.setBounds(330, 490, 260, 40);

        jTextField_numOfAttcks.setToolTipText("Number of Attacks");
        getContentPane().add(jTextField_numOfAttcks);
        jTextField_numOfAttcks.setBounds(150, 490, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/robot2_small.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 550, 90, 120);

        jTextArea_RewardsStatusText.setEditable(false);
        jTextArea_RewardsStatusText.setColumns(20);
        jTextArea_RewardsStatusText.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextArea_RewardsStatusText.setForeground(new java.awt.Color(102, 51, 0));
        jTextArea_RewardsStatusText.setRows(5);
        jTextArea_RewardsStatusText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea_RewardsStatusTextMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_RewardsStatusText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 570, 480, 100);

        jLabel_ConnectedBots.setText("Number of GETS");
        getContentPane().add(jLabel_ConnectedBots);
        jLabel_ConnectedBots.setBounds(30, 500, 120, 20);

        jLabel_DDOSURL1.setText("DDOS >>> URL");
        getContentPane().add(jLabel_DDOSURL1);
        jLabel_DDOSURL1.setBounds(30, 160, 110, 20);

        jLabel_ServerStatus1.setText("Server Status");
        getContentPane().add(jLabel_ServerStatus1);
        jLabel_ServerStatus1.setBounds(30, 200, 100, 20);

        jLabel_ConnectedBots1.setText("Bots - Performance >> Number of GETS/s");
        getContentPane().add(jLabel_ConnectedBots1);
        jLabel_ConnectedBots1.setBounds(20, 360, 280, 20);

        jLabel_ConnectedBots2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_ConnectedBots2.setText("Bots - Rewards");
        getContentPane().add(jLabel_ConnectedBots2);
        jLabel_ConnectedBots2.setBounds(100, 550, 100, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/AtckNowlogoSen.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, -20, 220, 120);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("© Senura Dissanayake");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 680, 150, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/whiteCol.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendDDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendDDOSActionPerformed

//        if(ServerConnection.closeTheConnection()){
//            buttonSendDDOS.setEnabled(false);
//        }

     String URLtext=jTextField_HostAddress.getText();
     
     if(URLValidate.isUrlValid(URLtext))
     {
         ServerConnection.setDDOSURL(URLtext);//("https://httpbin.org/ip");
         buttonSendDDOS.setEnabled(false);//hide button
         jButton_startDDOSAttck.setEnabled(true);
     }
     else{
         msgbox(URLtext+" is not a valid Host Address\n Make sure protocols are there (https/http etc.)");
     }



    }//GEN-LAST:event_buttonSendDDOSActionPerformed

    private void buttonStartConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartConnectionActionPerformed
        // TODO add your handling code here:

            boolean isServerStarted = ServerConnection.start();
            
            if(isServerStarted)  {
                buttonSendDDOS.setEnabled(true);
                buttonStartConnection.setEnabled(false);
            }
            else msgbox("Could not start the connection");
           
        
    }//GEN-LAST:event_buttonStartConnectionActionPerformed

    private void jTextField_HostAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HostAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HostAddressActionPerformed

    private void jButton_startDDOSAttckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startDDOSAttckActionPerformed
        try{
            ClientControllerCon.sendAttackCountToController(Integer.parseInt(jTextField_numOfAttcks.getText()));
            jButton_startDDOSAttck.setEnabled(false);
            jTextField_numOfAttcks.setEditable(false);
            ClientControllerCon.setTimerToUpdateRewardsStatus();
        }catch(NumberFormatException ex){
            msgbox("Number of Attacks is not a valid number\n Description:"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton_startDDOSAttckActionPerformed

    private void jTextArea_RewardsStatusTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea_RewardsStatusTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea_RewardsStatusTextMouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered

        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("https://github.com/SenuraMalaka"));
            } catch (URISyntaxException | IOException ex) {
                //
            }
}
        
        
    }//GEN-LAST:event_jLabel5MouseEntered

    
    
    
    
    private void msgbox(String s){
   javax.swing.JOptionPane.showMessageDialog(null, s);
        }
    
    public static void rewardsTextUpdate(String text){
    jTextArea_RewardsStatusText.setText(text);
    }
    
    
    
    
    
    public static void appendToStatusText(String status){
    
        jTextAreaStatus.append(status);
    }
    
    public static void showClientStatus(String status){
        jTextArea_ClientStatus.setText(status);
    }
    
    
    
    
    public void restartApplication() throws URISyntaxException, IOException
{
  final String javaBin = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";
  final File currentJar = new File(MainMenu.class.getProtectionDomain().getCodeSource().getLocation().toURI());

  /* is it a jar file? */
  if(!currentJar.getName().endsWith(".jar"))
    return;

  /* Build command: java -jar application.jar */
  final ArrayList<String> command = new ArrayList<String>();
  command.add(javaBin);
  command.add("-jar");
  command.add(currentJar.getPath());

  final ProcessBuilder builder = new ProcessBuilder(command);
  builder.start();
  System.exit(0);
}
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSendDDOS;
    private javax.swing.JButton buttonStartConnection;
    private javax.swing.JButton jButton_startDDOSAttck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_ConnectedBots;
    private javax.swing.JLabel jLabel_ConnectedBots1;
    private javax.swing.JLabel jLabel_ConnectedBots2;
    private javax.swing.JLabel jLabel_DDOSURL1;
    private javax.swing.JLabel jLabel_ServerStatus1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_ClientStatus;
    private javax.swing.JScrollPane jScrollPane_Status;
    private static javax.swing.JTextArea jTextAreaStatus;
    private static javax.swing.JTextArea jTextArea_ClientStatus;
    private static javax.swing.JTextArea jTextArea_RewardsStatusText;
    private javax.swing.JTextField jTextField_HostAddress;
    private javax.swing.JTextField jTextField_numOfAttcks;
    // End of variables declaration//GEN-END:variables
}
